#include "types.h"
#include <Adafruit_GFX.h>
#include <Adafruit_SSD1306.h>



//when creating a new board config, set unused pins to PIN_NOT_USED
// for FET_DRIVER, set drvEN to the fet pin
// for ESC_DRIVER, set drvEN to the esc pin
// depending on I2C pins 
const boards_t trifolium_v1_2_fet_driver = {
    .pusherDriverType = FET_DRIVER,
    .esc1 = 0,
    .esc2 = 1,
    .esc3 = 2,
    .esc4 = 3,
    .telem = 4,
    .I2C_SCL = 15,
    .I2C_SDA = 14,
    .I2C_HW_BLK = i2c1,
    .IO2 = 18,
    .IO5 = 19,
    .IO6 = 20,
    .IO1 = 21,
    .IO3 = 9,
    .IO4 = 10,
    .batteryADC = 28,
    .escADC = 26,
    .drvADC = PIN_NOT_USED,
    .drvNSLEEP = PIN_NOT_USED,    
    .drvEN = 24,
    .drvPH = PIN_NOT_USED,
    .drvMOSI = PIN_NOT_USED,
    .drvMISO = PIN_NOT_USED,
    .drvNSCS = PIN_NOT_USED,
    .drvSCLK = PIN_NOT_USED,
    .LED_DATA = PIN_NOT_USED,
    .ESC_ENABLE = PIN_NOT_USED,
};


const boards_t trifolium_v1_2_esc_driver = {
    .pusherDriverType = ESC_DRIVER, 
    .esc1 = 0,
    .esc2 = 1,
    .esc3 = 2,
    .esc4 = 3,
    .telem = 4,
    .I2C_SCL = 15,
    .I2C_SDA = 14,
    .I2C_HW_BLK = i2c1,
    .IO2 = 18,
    .IO5 = 19,
    .IO6 = 20,
    .IO1 = 21,
    .IO3 = 9,
    .IO4 = 10,
    .batteryADC = 28,
    .escADC = 26,
    .drvADC = PIN_NOT_USED,
    .drvNSLEEP = PIN_NOT_USED,    
    .drvEN = 2,
    .drvPH = PIN_NOT_USED,
    .drvMOSI = PIN_NOT_USED,
    .drvMISO = PIN_NOT_USED,
    .drvNSCS = PIN_NOT_USED,
    .drvSCLK = PIN_NOT_USED,
    .LED_DATA = PIN_NOT_USED,
    .ESC_ENABLE = PIN_NOT_USED,
};




const boards_t trifolium_v1_1_fet_driver = {
    .pusherDriverType = FET_DRIVER,
    .esc1 = 0,
    .esc2 = 1,
    .esc3 = 2,
    .esc4 = 3,
    .telem = 4,
    .I2C_SCL = 15,
    .I2C_SDA = 14,
    .I2C_HW_BLK = i2c1,
    .IO2 = 18,
    .IO5 = 19,
    .IO6 = 20,
    .IO1 = 21,
    .IO3 = 9,
    .IO4 = 10,
    .batteryADC = 28,
    .escADC = 26,
    .drvADC = PIN_NOT_USED,
    .drvNSLEEP = PIN_NOT_USED,    
    .drvEN = 27,
    .drvPH = PIN_NOT_USED,
    .drvMOSI = PIN_NOT_USED,
    .drvMISO = PIN_NOT_USED,
    .drvNSCS = PIN_NOT_USED,
    .drvSCLK = PIN_NOT_USED,
    .LED_DATA = PIN_NOT_USED,
    .ESC_ENABLE = PIN_NOT_USED,
};


const boards_t trifolium_v1_1_esc_driver = {
    .pusherDriverType = ESC_DRIVER, 
    .esc1 = 0,
    .esc2 = 1,
    .esc3 = 2,
    .esc4 = 3,
    .telem = 4,
    .I2C_SCL = 15,
    .I2C_SDA = 14,
    .I2C_HW_BLK = i2c1,
    .IO2 = 18,
    .IO5 = 19,
    .IO6 = 20,
    .IO1 = 21,
    .IO3 = 9,
    .IO4 = 10,
    .batteryADC = 28,
    .escADC = 26,
    .drvADC = PIN_NOT_USED,
    .drvNSLEEP = PIN_NOT_USED,    
    .drvEN = 2,
    .drvPH = PIN_NOT_USED,
    .drvMOSI = PIN_NOT_USED,
    .drvMISO = PIN_NOT_USED,
    .drvNSCS = PIN_NOT_USED,
    .drvSCLK = PIN_NOT_USED,
    .LED_DATA = PIN_NOT_USED,
    .ESC_ENABLE = PIN_NOT_USED,
};

const boards_t trifolium_v1_0_fet_driver = {
    .pusherDriverType = FET_DRIVER,
    .esc1 = 0,
    .esc2 = 1,
    .esc3 = 2,
    .esc4 = 3,
    .telem = PIN_NOT_USED,
    .I2C_SCL = 15,
    .I2C_SDA = 14,
    .I2C_HW_BLK = i2c1,
    .IO2 = 18,
    .IO5 = 19,
    .IO6 = 20,
    .IO1 = 21,
    .IO3 = 9,
    .IO4 = 10,
    .batteryADC = PIN_NOT_USED,
    .escADC = PIN_NOT_USED,
    .drvADC = PIN_NOT_USED,
    .drvNSLEEP = PIN_NOT_USED,    
    .drvEN = 27,
    .drvPH = PIN_NOT_USED,
    .drvMOSI = PIN_NOT_USED,
    .drvMISO = PIN_NOT_USED,
    .drvNSCS = PIN_NOT_USED,
    .drvSCLK = PIN_NOT_USED,
    .LED_DATA = PIN_NOT_USED,
    .ESC_ENABLE = PIN_NOT_USED,
};


const boards_t trifolium_v1_0_esc_driver = {
    .pusherDriverType = ESC_DRIVER, 
    .esc1 = 0,
    .esc2 = 1,
    .esc3 = 2,
    .esc4 = 3,
    .telem = PIN_NOT_USED,
    .I2C_SCL = 15,
    .I2C_SDA = 14,
    .I2C_HW_BLK = i2c1,
    .IO2 = 18,
    .IO5 = 19,
    .IO6 = 20,
    .IO1 = 21,
    .IO3 = 9,
    .IO4 = 10,
    .batteryADC = PIN_NOT_USED,
    .escADC = PIN_NOT_USED,
    .drvADC = PIN_NOT_USED,
    .drvNSLEEP = PIN_NOT_USED,    
    .drvEN = 2,
    .drvPH = PIN_NOT_USED,
    .drvMOSI = PIN_NOT_USED,
    .drvMISO = PIN_NOT_USED,
    .drvNSCS = PIN_NOT_USED,
    .drvSCLK = PIN_NOT_USED,
    .LED_DATA = PIN_NOT_USED,
    .ESC_ENABLE = PIN_NOT_USED,
};


const boards_t pico_zero_diana = {
    .pusherDriverType = FET_DRIVER, 
    .esc1 = 0,
    .esc2 = 1,
    .esc3 = 2,
    .esc4 = 3,
    .telem = PIN_NOT_USED,
    .I2C_SCL = 5,
    .I2C_SDA = 4,
    .I2C_HW_BLK = i2c0,
    .IO2 = 4,
    .IO5 = 8,
    .IO6 = 6,
    .IO1 = 3,
    .IO3 = 5,
    .IO4 = 12,
    .batteryADC = PIN_NOT_USED,
    .escADC = PIN_NOT_USED,
    .drvADC = PIN_NOT_USED,
    .drvNSLEEP = PIN_NOT_USED,    
    .drvEN = 11,
    .drvPH = PIN_NOT_USED,
    .drvMOSI = PIN_NOT_USED,
    .drvMISO = PIN_NOT_USED,
    .drvNSCS = PIN_NOT_USED,
    .drvSCLK = PIN_NOT_USED,
    .LED_DATA = 24,
    .ESC_ENABLE = PIN_NOT_USED,
};


const boards_t pico_zero = {
    .pusherDriverType = FET_DRIVER, 
    .esc1 = 0,
    .esc2 = 1,
    .esc3 = 2,
    .esc4 = 3,
    .telem = PIN_NOT_USED,
    .I2C_SCL = 5,
    .I2C_SDA = 4,
    .I2C_HW_BLK = i2c0,
    .IO2 = 7,
    .IO5 = 8,
    .IO6 = 9,
    .IO1 = 10,
    .IO3 = 11,
    .IO4 = 12,
    .batteryADC = 26,
    .escADC = 27,
    .drvADC = 28,
    .drvNSLEEP = 16,    
    .drvEN = 17,
    .drvPH = 18,
    .drvMOSI = 19,
    .drvMISO = 20,
    .drvNSCS = 21,
    .drvSCLK = 22,
    .LED_DATA = 24,
    .ESC_ENABLE = 25,
};


const boards_t rune_0_2 = {
    .pusherDriverType = DRV_DRIVER, 
    .esc1 = 0,
    .esc2 = 1,
    .esc3 = 2,
    .esc4 = 3,
    .telem = 4,
    .I2C_SCL = 5,
    .I2C_SDA = 6,
    .I2C_HW_BLK = i2c0, // rune i2c messed up
    .IO2 = 7,
    .IO5 = 8,
    .IO6 = 9,
    .IO1 = 10,
    .IO3 = 11,
    .IO4 = 12,
    .batteryADC = 26,
    .escADC = 27,
    .drvADC = 28,
    .drvNSLEEP = 16,    
    .drvEN = 17,
    .drvPH = 18,
    .drvMOSI = 19,
    .drvMISO = 20,
    .drvNSCS = 21,
    .drvSCLK = 22,
    .LED_DATA = 24,
    .ESC_ENABLE = 25,
};

