#include "menuItem.h"

extern bool firstBoot;

#define MAX_PROFILE_COUNT 5
#define PROFILE_EEPROM_SIZE 400
#define EEPROM_INIT_MAGIC_NUMBER 0xEB955ED833211587ULL // Random number to check if EEPROM is initialized
#define EEPROM_SIZE 4096

enum EepromPos {
	// Profile dependent settings 0-399 ... 1600-1999, 400 bytes each
	EEPROM_PROFILE_SETTINGS_START = 0,
	EEPROM_POS_TARGET_RPM_FRONT = 0,
	EEPROM_POS_IDLE_RPM = 4,
	EEPROM_POS_RAMPDOWN_SPEED = 8,
	EEPROM_POS_RAMPUP_TIMEOUT = 10,
	EEPROM_POS_IDLE_ENABLED = 12,
	EEPROM_POS_FIRE_MODE = 13,
	EEPROM_POS_DARTS_PER_SECOND = 14,
	EEPROM_POS_BURST_COUNT = 15,
	EEPROM_POS_PROFILE_NAME = 16,
	EEPROM_POS_PROFILE_COLOR_RED = 32,
	EEPROM_POS_PROFILE_COLOR_GREEN = 33,
	EEPROM_POS_PROFILE_COLOR_BLUE = 34,
	EEPROM_POS_FRONT_REAR_RATIO = 35,
	EEPROM_POS_RPM_IN_RANGE_TIME = 37,
	EEPROM_POS_RPM_THRES_PCT = 39,
#if HW_VERSION == 2
	EEPROM_POS_AUTO_TIMING = 40,
	EEPROM_POS_DPS_LIMIT = 41,
#endif
	EEPROM_POS_REV_AFTER_FIRE = 42,
	EEPROM_POS_BURST_KEEP_FIRE = 44,

	// EEPROM metadata start at 2000
	EEPROM_INFO_START = 2000,
	EEPROM_POS_MAGIC_NUMBER = 2000,
	EEPROM_POS_VERSION_MAJOR = 2008,
	EEPROM_POS_VERSION_MINOR = 2009,
	EEPROM_POS_VERSION_PATCH = 2010,

	// General settings start at 2048
	EEPROM_GENERAL_SETTINGS_START = 2048,
	EEPROM_POS_DEVICE_NAME = 2048,
	EEPROM_POS_OWNER_NAME = 2064,
	EEPROM_POS_OWNER_CONTACT = 2096,
	EEPROM_POS_PROFILE_COUNT = 2128,
	EEPROM_POS_BAT_WARN = 2129,
	EEPROM_POS_BAT_SHUTDOWN = 2130,
	EEPROM_POS_FIRE_WO_MAG = 2131,
	EEPROM_POS_FIRE_EMPTY = 2132,
	EEPROM_POS_MIN_THROTTLE = 2133,
	EEPROM_POS_JCAL_CENTER_X = 2134,
	EEPROM_POS_JCAL_CENTER_Y = 2136,
	EEPROM_POS_JCAL_MIN_X = 2138,
	EEPROM_POS_JCAL_MAX_X = 2140,
	EEPROM_POS_JCAL_MIN_Y = 2142,
	EEPROM_POS_JCAL_MAX_Y = 2144,
	EEPROM_POS_PUSH_DURATION = 2146,
	EEPROM_POS_RETRACT_DURATION = 2147,
	EEPROM_POS_ESC_MAX_TEMP = 2148,
	EEPROM_POS_MAG_SIZE = 2149,
	EEPROM_POS_BAT_CELLS = 2150,
	EEPROM_POS_MOTOR_LAYOUT = 2151,
	EEPROM_POS_INACTIVITY_TIMEOUT = 2152,
	EEPROM_POS_ROTATION_SENSITIVITY = 2153,
#if HW_VERSION == 2
	EEPROM_POS_BEEP_ON_MAG_CHANGE = 2154,
	EEPROM_POS_FALL_DETECTION = 2155,
	EEPROM_POS_FIRE_ANGLE_LIMIT = 2156,
#endif
	EEPROM_POS_EXTENDED_RPM_RANGE = 2157,
	EEPROM_POS_PID_P = 2158,
	EEPROM_POS_PID_I = 2160,
	EEPROM_POS_PID_D = 2162,
	EEPROM_POS_MOTOR_KV = 2164,
	EEPROM_POS_SETTINGS_BEEP = 2166,
	EEPROM_POS_PUSHER_DECAY = 2167,
	EEPROM_POS_BOOT_SAFE = 2169,
	EEPROM_POS_STALL_DETECTION = 2170,
#if HW_VERSION == 2
	EEPROM_POS_FAST_STANDBY = 2171,
#endif
	EEPROM_POS_BAT_OFFSET = 2172,
	EEPROM_POS_TOF_HIGH = 2173,
	EEPROM_POS_TOF_LOW = 2174,
	EEPROM_POS_TOURNAMENT_ENABLED = 2175,
	EEPROM_POS_TOURNAMENT_MAXRPM = 2176,
	EEPROM_POS_TOURNAMENT_MAXDPS = 2180,
	EEPROM_POS_TOURNAMENT_ALLOW_SEMI_AUTO = 2181,
	EEPROM_POS_TOURNAMENT_ALLOW_FULL_AUTO = 2182,
	EEPROM_POS_TOURNAMENT_INVERT_SCREEN = 2183,
	EEPROM_POS_TOURNAMENT_BLOCK_MENU = 2184,
#if HW_VERSION == 2
	EEPROM_POS_LED_BRIGHTNESS = 2185,
#endif
	EEPROM_POS_TIMEOUT_MODE = 2186,
#if HW_VERSION == 2
	EEPROM_POS_STARTUP_SOUND = 2187,
#endif
	EEPROM_POS_IDLE_ONLY_WITH_MAG = 2188,
	EEPROM_POS_ESC_TEMP_OFFSETS = 2189,

	// Runtime options, not stored in EEPROM
	EEPROM_RUNTIME_OPTION = 0x7FFF,
};

void eepromInit();
bool clearEeprom(MenuItem *_item);
